version = 0.1
[default.deploy.parameters]
stack_name = "interphlix"
resolve_s3 = true
s3_prefix = "interphlix"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
