AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for interphlix-authentication Lambda function

Resources:
  InterphlixAuthenticationApi:
    Type: AWS::Serverless::HttpApi

  InterphlixAuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: interphlix-authentication
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: target/lambda/authentication/bootstrap.zip
      Architectures:
        - x86_64
      MemorySize: 1024
      Events:
        ApiGateway:
          Type: HttpApi
          Properties:
            ApiId: !Ref InterphlixAuthenticationApi
            Path: /
            Method: any

  InterphlixUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Interphlix-Users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: B
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  VerificationCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Verification-Codes
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: B
        - AttributeName: created_at
          AttributeType: N
        - AttributeName: uuid
          AttributeType: B
        - AttributeName: expires
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UuidIndex
          KeySchema:
            - AttributeName: uuid
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
      
Outputs:
  InterphlixAuthenticationApiUrl:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${InterphlixAuthenticationApi}.execute-api.${AWS::Region}.amazonaws.com/"
