[package]
name = "keyrotator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
lambda_runtime = "0.13.0"
ed25519-dalek = "2.1.1"
aws-sdk-ssm = "1.59.0"
base64 = "0.22.1"